# Generated by Django 5.2.7 on 2025-10-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom unique de la catégorie (ex: Cardiologie)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description optionnelle de la catégorie."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="raw_llm_suggestions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stocke les suggestions brutes du LLM (catégories, etc.) pour revue par l'expert.",
            ),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Catégories médicales associées à ce cas.",
                related_name="cases",
                to="cases.category",
            ),
        ),
    ]
