# Generated by Django 5.2.7 on 2025-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_category_clinicalcase_raw_llm_suggestions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalcase",
            name="etat_civil",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
