# Generated by Django 5.2.7 on 2025-11-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_clinicalcase_etat_civil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalcase",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
