# Generated by Django 5.2.7 on 2025-11-06 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_alter_clinicalcase_profession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="case_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="case_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="cases.category"
            ),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="groupe_sanguin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="learning_objectives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="mode_de_vie",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="nombre_enfant",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="raw_llm_suggestions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="source_fultang_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="complementaryexam",
            name="nom",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="complementaryexam",
            name="resultat",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="currenttreatment",
            name="date_debut",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="currenttreatment",
            name="efficacite",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currenttreatment",
            name="nom",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="currenttreatment",
            name="posologie",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="physicalfinding",
            name="nom_examen",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="physicalfinding",
            name="resultat_observation",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="activite_declenchante",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="date_debut",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="degre",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="duree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="evolution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="frequence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="localisation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
