# Generated by Django 5.2.7 on 2025-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_category_description_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalcase",
            name="key_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des questions clés que l'apprenant doit poser.",
                null=True,
            ),
        ),
    ]
