# Generated by Django 5.2.7 on 2026-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_clinicalcase_key_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalcase",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Motif du rejet (rempli par l'expert)", null=True
            ),
        ),
    ]
