# Generated by Django 5.2.7 on 2026-01-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_clinicalcase_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalcase",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Facile", "Facile"),
                    ("Moyen", "Moyen"),
                    ("Difficile", "Difficile"),
                ],
                default="Moyen",
                max_length=20,
                null=True,
            ),
        ),
    ]
