# Generated by Django 5.2.7 on 2026-01-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_clinicalcase_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalcase",
            name="reasoning_graph",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structure nœuds/liens représentant le raisonnement clinique (généré par IA).",
                null=True,
            ),
        ),
    ]
