# Generated by Django 5.2.7 on 2026-01-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_clinicalcase_reasoning_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="complementaryexam",
            name="anatomie",
            field=models.CharField(
                blank=True,
                help_text="Zone anatomique concernée",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="date",
            field=models.CharField(
                blank=True, help_text="Date ou Date début", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="date_fin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="declencheur",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="manifestation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="nom",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="nombre_grossesse",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="traitement_duree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="traitement_nom",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="traitement_posologie",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="description",
            field=models.TextField(help_text="Description générale"),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("maladie", "Maladie"),
                    ("chirurgie", "Chirurgie"),
                    ("familial", "Familiaux"),
                    ("allergie", "Allergies"),
                    ("obstetrical", "Obstétricaux"),
                ],
                max_length=20,
            ),
        ),
    ]
