# Generated by Django 5.2.7 on 2026-01-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_complementaryexam_anatomie_medicalhistory_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalcase",
            name="rejection_reason",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Détail du rejet : { 'global': '...', 'fields': { 'age': 'Erreur', ... } }",
                null=True,
            ),
        ),
    ]
