# Generated by Django 5.2.7 on 2026-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_alter_clinicalcase_rejection_reason"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Specialty",
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
            },
        ),
        migrations.RemoveField(
            model_name="clinicalcase",
            name="categories",
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Spécialités médicales concernées.",
                related_name="cases",
                to="cases.specialty",
            ),
        ),
    ]
