# Generated by Django 5.2.7 on 2026-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_rename_category_specialty_alter_specialty_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalcase",
            name="common_pitfalls",
            field=models.TextField(
                blank=True, help_text="Erreurs fréquentes à éviter", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="initial_statement",
            field=models.TextField(blank=True, help_text="Phrase d'intro", null=True),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="patient_persona",
            field=models.TextField(
                blank=True, help_text="Personnalité du patient", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="system_prompt_patient",
            field=models.TextField(
                blank=True, help_text="Prompt système exact", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicalcase",
            name="system_prompt_tutor",
            field=models.TextField(
                blank=True, help_text="Prompt tuteur exact", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="key_questions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="reasoning_graph",
            field=models.JSONField(
                blank=True, default=dict, help_text="Graphe de logique", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="rejection_reason",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalcase",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="cases.specialty"
            ),
        ),
        migrations.AlterField(
            model_name="complementaryexam",
            name="anatomie",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="description",
            field=models.TextField(),
        ),
    ]
