# Generated by Django 5.2.7 on 2025-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="skill_matrix",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Niveau de compétence par catégorie (Score moyen sur 100)",
            ),
        ),
    ]
