# Generated by Django 5.2.7 on 2026-01-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_skill_matrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("APPRENANT", "Apprenant"),
                    ("EXPERT", "Expert"),
                    ("ADMIN", "Administrateur"),
                ],
                default="APPRENANT",
                max_length=20,
            ),
        ),
    ]
