# Generated by Django 5.2.7 on 2026-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="detailed_profile_analysis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Analyse qualitative globale de l'apprenant générée par l'IA.",
            ),
        ),
    ]
