# Generated by Django 5.2.7 on 2025-11-06 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0005_alter_category_description_alter_category_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En Cours"),
                            ("completed", "Terminée"),
                            ("canceled", "Annulée"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de début de la session.",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de fin de la session.",
                        null=True,
                    ),
                ),
                (
                    "apprenant",
                    models.ForeignKey(
                        help_text="L'utilisateur qui participe à la simulation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Le cas clinique utilisé pour cette simulation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulation_sessions",
                        to="cases.clinicalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de Simulation",
                "verbose_name_plural": "Sessions de Simulation",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("APPRENANT", "Apprenant"),
                            ("PATIENT_IA", "Patient IA"),
                            ("SYSTEM", "Système"),
                        ],
                        help_text="Qui a envoyé le message.",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Le contenu textuel du message."),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure d'enregistrement du message.",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="La session à laquelle ce message appartient.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="simulation.simulationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de Chat",
                "verbose_name_plural": "Messages de Chat",
                "ordering": ["timestamp"],
            },
        ),
    ]
