# Generated by Django 5.2.7 on 2025-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[
                    ("APPRENANT", "Apprenant"),
                    ("PATIENT_IA", "Patient IA"),
                    ("SYSTEM", "Système"),
                    ("TUTEUR", "Tuteur Pédagogique"),
                ],
                help_text="Qui a envoyé le message.",
                max_length=20,
            ),
        ),
    ]
