# Generated by Django 5.2.7 on 2026-01-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_alter_chatmessage_sender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="simulationsession",
            name="student_diagnosis",
            field=models.TextField(
                blank=True,
                help_text="Le diagnostic final posé par l'étudiant.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationsession",
            name="student_prescription",
            field=models.TextField(
                blank=True,
                help_text="Le traitement et la conduite à tenir proposés.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[
                    ("APPRENANT", "Apprenant"),
                    ("PATIENT_IA", "Patient IA"),
                    ("TUTEUR", "Tuteur Pédagogique"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="simulation.simulationsession",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
